# Generated by Django 3.0.7 on 2022-04-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220406_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryLang',
        ),
    ]
