# Generated by Django 3.0.7 on 2022-04-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_categorylang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
