# Generated by Django 3.0.7 on 2022-04-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220405_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='note',
        ),
    ]
